In [202]:
a = "flying fish flew by the space station"
b = "we will not allow you to bring your pet armadillo along"
c = "he figured a few sticks of dynamite were easier than a fishing pole to catch fish"

In [203]:
import numpy as np

def shingle(str, k = 2):
    #result = set()
    #for i in range(len(str) - k + 1):
        #result.add(str[i:i+k])
    result = []
    for i in range(len(str) - k+1):
        result.append(str[i:i+k])
    return set(result)
    return result

shingles_a = shingle(a)
shingles_b = shingle(b)
shingles_c = shingle(c)
sa = list(shingles_a)
sb = list(shingles_b)
sc = list(shingles_c)
print("shingles_a", shingles_a)
print("shingles_b", shingles_b)
print("shingles_c", shingles_c)

shingles_a {'ti', 'io', 'th', 'h ', 'ew', 'e ', 'in', 'by', 'is', 'yi', 'ta', 'at', 'he', ' s', 'sh', ' b', 'on', ' f', 'ce', 'pa', 'sp', 'le', 'y ', 'ac', 'ng', 'w ', 'st', 'fi', 'ly', ' t', 'fl', 'g '}
shingles_b {'t ', 'ar', ' p', 'ma', 'ow', 'e ', 'wi', 'br', 'no', 'di', 'l ', ' a', 'al', 'in', ' y', 'we', 'et', 'pe', 'ri', 'ou', 'o ', ' n', 'ur', 'u ', ' b', 'ot', 'rm', 'on', 'to', 'lo', 'yo', 'ad', 'il', 'w ', 'ng', 'll', ' w', ' t', 'r ', 'g '}
shingles_c {'ed', 'ti', 'mi', 'ie', 'hi', 'ch', 'th', 'ca', ' p', 'h ', 'ew', 'a ', 'e ', 'gu', 'ol', 'na', 'ea', 'it', ' a', 'in', 'is', 'yn', ' w', 'an', 'we', 'as', 'f ', ' o', 'am', 'te', 'at', 'he', 'fe', 'n ', 'ks', 'ur', 'po', ' s', 'o ', 'sh', 'ck', 'er', 'ic', ' e', ' f', 'tc', 'to', ' t', 'ha', 'ig', 'le', ' c', 'd ', 're', 'si', 'dy', 'w ', 'ng', 'st', 'fi', 's ', 'of', ' d', 'r ', 'g '}


In [204]:
vocab = list(shingles_a.union(shingles_b).union(shingles_c))

print("len vocab", len(vocab))
print("len shingles_a", len(sa))
print("len shingles_b", len(sb))
print("len shingles_c", len(sc))


len vocab 102
len shingles_a 32
len shingles_b 40
len shingles_c 65


In [206]:
sparce_a = np.empty(len(vocab))
sparce_b = np.empty(len(vocab))
sparce_c = np.empty(len(vocab))
for i in range(len(vocab)):
    sparce_a[i] = 1 if vocab[i] in shingles_a else 0
    sparce_b[i] = 1 if vocab[i] in shingles_b else 0
    sparce_c[i] = 1 if vocab[i] in shingles_c else 0
print("sparce a", sparce_a)
print("len sparce a", len(sparce_a))

sparce a [0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0.
 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0.
 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.
 1. 0. 1. 1. 1. 0.]
len sparce a 102


In [207]:
sentences = np.array([sparce_a, sparce_b, sparce_c])
sentences

array([[0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
        1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
        1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 0., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.

In [208]:
def get_MinHash(sentences, num = 2):
    row_numbers = list(range(1, len(sentences[0])+1))
    shuffle = row_numbers
    signature = np.empty([num, len(sentences)])
    
    for sh in range(num):
        np.random.shuffle(shuffle)
        
        for j in range(len(sentences)):            
            i = 0
            while sentences[j][shuffle[i] - 1]== 0 and i < len(shuffle):
                i += 1
            signature[sh][j] = shuffle[i]
            
    return signature

signature = get_MinHash(sentences, 40)
signature.shape

(40, 3)

In [209]:
def jaccard(a: set, b: set):
    return len(a.intersection(b)) / len(a.union(b))

print("jaccard a b ", (jaccard(shingles_a, shingles_b), jaccard(set(signature[:, 0]), set(signature[:,1]))))
print("jaccard a c ", (jaccard(shingles_a, shingles_c), jaccard(set(signature[:, 0]), set(signature[:,2]))))
print("jaccard b c", (jaccard(shingles_b, shingles_c), jaccard(set(signature[:, 1]), set(signature[:,2]))))

jaccard a b  (0.125, 0.047619047619047616)
jaccard a c  (0.24358974358974358, 0.15)
jaccard b c (0.15384615384615385, 0.1111111111111111)


In [210]:
def get_split_vector(signature, bands):
    r = int(signature.shape[0]/bands)
    subvectors = []
    for i in range(0, len(signature), r):
        subvectors.append(signature[i : i+r])
    return subvectors

subvectors = get_split_vector(signature, bands = 20)
subvectors

[array([[  8.,  91.,  41.],
        [100.,  61.,  39.]]),
 array([[49., 69., 96.],
        [ 8., 18., 15.]]),
 array([[44., 38., 41.],
        [42., 89., 64.]]),
 array([[97., 50., 97.],
        [73., 85.,  4.]]),
 array([[ 92., 102., 102.],
        [  2.,  82.,   2.]]),
 array([[50., 85., 85.],
        [72., 29., 86.]]),
 array([[  9.,  13.,   9.],
        [ 30., 102.,   1.]]),
 array([[45., 61., 64.],
        [40., 75., 22.]]),
 array([[19., 29., 19.],
        [ 9., 18.,  9.]]),
 array([[92., 68., 11.],
        [ 8.,  7., 93.]]),
 array([[97., 84., 84.],
        [45., 84., 84.]]),
 array([[97., 38., 97.],
        [99., 91., 70.]]),
 array([[ 2., 88.,  2.],
        [88., 65., 41.]]),
 array([[40., 89., 85.],
        [31., 61., 81.]]),
 array([[52., 82., 52.],
        [42., 55., 55.]]),
 array([[30., 67., 30.],
        [ 2., 38.,  2.]]),
 array([[50., 22., 22.],
        [40., 75., 35.]]),
 array([[ 40.,  74.,  28.],
        [ 92., 102., 102.]]),
 array([[40., 58., 86.],
        [45., 4

In [211]:
for s1 in range(subvectors[0].shape[1] - 1):
    for s2 in range(s1 + 1, subvectors[0].shape[1]):
        for i in range(len(subvectors)):     
            if np.array_equal(subvectors[i][:, s1],subvectors[i][:, s2]):
                print("candidates pair", subvectors[i][:, s1])
                print("s1, s2", (s1, s2))
                

candidates pair [19.  9.]
s1, s2 (0, 2)
candidates pair [30.  2.]
s1, s2 (0, 2)
candidates pair [84. 84.]
s1, s2 (1, 2)
